# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-01 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('Player', '0001_initial'),
        ('Seasons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalAndAssistAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Goal_Scorer', models.CharField(max_length=30)),
                ('Assist_Giver', models.CharField(max_length=30)),
                ('Bonus', models.BooleanField(default=False)),
                ('By_Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Player.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='GoalAndAssistAnswerSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Goal_Scorer', models.CharField(max_length=30)),
                ('Assist_Giver', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GroupRanksAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank_1', models.CharField(max_length=30)),
                ('Rank_2', models.CharField(max_length=30)),
                ('Rank_3', models.CharField(max_length=30)),
                ('Rank_4', models.CharField(max_length=30)),
                ('Bonus', models.BooleanField(default=False)),
                ('By_Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Player.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='GroupRanksAnswerSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rank_1', models.CharField(max_length=30)),
                ('Rank_2', models.CharField(max_length=30)),
                ('Rank_3', models.CharField(max_length=30)),
                ('Rank_4', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LineupAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Player_1', models.CharField(max_length=30)),
                ('Player_2', models.CharField(max_length=30)),
                ('Player_3', models.CharField(max_length=30)),
                ('Player_4', models.CharField(max_length=30)),
                ('Player_5', models.CharField(max_length=30)),
                ('Player_6', models.CharField(max_length=30)),
                ('Player_7', models.CharField(max_length=30)),
                ('Player_8', models.CharField(max_length=30)),
                ('Player_9', models.CharField(max_length=30)),
                ('Player_10', models.CharField(max_length=30)),
                ('Player_11', models.CharField(max_length=30)),
                ('Bonus', models.BooleanField(default=False)),
                ('By_Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Player.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='LineupAnswerSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Player_1', models.CharField(max_length=30)),
                ('Player_2', models.CharField(max_length=30)),
                ('Player_3', models.CharField(max_length=30)),
                ('Player_4', models.CharField(max_length=30)),
                ('Player_5', models.CharField(max_length=30)),
                ('Player_6', models.CharField(max_length=30)),
                ('Player_7', models.CharField(max_length=30)),
                ('Player_8', models.CharField(max_length=30)),
                ('Player_9', models.CharField(max_length=30)),
                ('Player_10', models.CharField(max_length=30)),
                ('Player_11', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Matchday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MatchDay', models.CharField(max_length=2)),
                ('Deadline', models.DateTimeField()),
                ('Questions_By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Player.Profile')),
                ('Season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seasons.AllSeason')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_Number', models.CharField(max_length=2)),
                ('Question', models.TextField()),
                ('Margin', models.IntegerField(default=0)),
                ('Bonus_Allowed', models.BooleanField(default=True)),
                ('Answer_Set_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Answer_Set_Type', to='contenttypes.ContentType')),
                ('Answer_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Answer_Type', to='contenttypes.ContentType')),
                ('For_Matchday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.Matchday')),
            ],
        ),
        migrations.CreateModel(
            name='ScorelineAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Home_Team_Score', models.IntegerField()),
                ('Away_Team_Score', models.IntegerField()),
                ('Bonus', models.BooleanField(default=False)),
                ('By_Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Player.Profile')),
                ('For_Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SA', to='Management.Question')),
            ],
        ),
        migrations.CreateModel(
            name='ScorelineAnswerSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Home_Team_Score', models.IntegerField()),
                ('Away_Team_Score', models.IntegerField()),
                ('For_Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.Question')),
            ],
        ),
        migrations.CreateModel(
            name='SingleIntegerAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.IntegerField()),
                ('Bonus', models.BooleanField(default=False)),
                ('By_Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Player.Profile')),
                ('For_Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SIA', to='Management.Question')),
            ],
        ),
        migrations.CreateModel(
            name='SingleIntegerAnswerSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.IntegerField()),
                ('For_Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.Question')),
            ],
        ),
        migrations.CreateModel(
            name='SinglePlayerTeamAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.CharField(max_length=30)),
                ('Bonus', models.BooleanField(default=False)),
                ('By_Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Player.Profile')),
                ('For_Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SPTA', to='Management.Question')),
            ],
        ),
        migrations.CreateModel(
            name='SinglePlayerTeamAnswerSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.CharField(max_length=30)),
                ('For_Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SPTAS', to='Management.Question')),
            ],
        ),
        migrations.CreateModel(
            name='TeamAndValueAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team', models.CharField(max_length=30)),
                ('Value', models.IntegerField()),
                ('Bonus', models.BooleanField(default=False)),
                ('By_Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Player.Profile')),
                ('For_Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TAVA', to='Management.Question')),
            ],
        ),
        migrations.CreateModel(
            name='TeamAndValueAnswerSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team', models.CharField(max_length=30)),
                ('Value', models.IntegerField()),
                ('For_Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.Question')),
            ],
        ),
        migrations.CreateModel(
            name='WinDrawLoseAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.CharField(choices=[('Win', 'Win'), ('Draw', 'Draw'), ('Lose', 'Lose')], max_length=30)),
                ('Bonus', models.BooleanField(default=False)),
                ('By_Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Player.Profile')),
                ('For_Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WDLA', to='Management.Question')),
            ],
        ),
        migrations.CreateModel(
            name='WinDrawLoseAnswerSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.CharField(choices=[('Win', 'Win'), ('Draw', 'Draw'), ('Lose', 'Lose')], max_length=30)),
                ('For_Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WDLAS', to='Management.Question')),
            ],
        ),
        migrations.CreateModel(
            name='YesNoAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('Bonus', models.BooleanField(default=False)),
                ('By_Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Player.Profile')),
                ('For_Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='YNA', to='Management.Question')),
            ],
        ),
        migrations.CreateModel(
            name='YesNoAnswerSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30)),
                ('For_Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='YNAS', to='Management.Question')),
            ],
        ),
        migrations.AddField(
            model_name='lineupanswerset',
            name='For_Question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.Question'),
        ),
        migrations.AddField(
            model_name='lineupanswer',
            name='For_Question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LA', to='Management.Question'),
        ),
        migrations.AddField(
            model_name='groupranksanswerset',
            name='For_Question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.Question'),
        ),
        migrations.AddField(
            model_name='groupranksanswer',
            name='For_Question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GRA', to='Management.Question'),
        ),
        migrations.AddField(
            model_name='goalandassistanswerset',
            name='For_Question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.Question'),
        ),
        migrations.AddField(
            model_name='goalandassistanswer',
            name='For_Question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GAAA', to='Management.Question'),
        ),
    ]
