# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 14:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Management', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Seasons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yesnoanswer',
            name='by_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='yesnoanswer',
            name='for_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='YNA', to='Management.Question'),
        ),
        migrations.AddField(
            model_name='windrawloseanswerset',
            name='for_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WDLAS', to='Management.Question'),
        ),
        migrations.AddField(
            model_name='windrawloseanswer',
            name='by_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='windrawloseanswer',
            name='for_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WDLA', to='Management.Question'),
        ),
        migrations.AddField(
            model_name='teamandvalueanswerset',
            name='for_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.Question'),
        ),
        migrations.AddField(
            model_name='teamandvalueanswer',
            name='by_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teamandvalueanswer',
            name='for_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TAVA', to='Management.Question'),
        ),
        migrations.AddField(
            model_name='singleplayerteamanswerset',
            name='for_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SPTAS', to='Management.Question'),
        ),
        migrations.AddField(
            model_name='singleplayerteamanswer',
            name='by_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='singleplayerteamanswer',
            name='for_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SPTA', to='Management.Question'),
        ),
        migrations.AddField(
            model_name='singleintegeranswerset',
            name='for_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.Question'),
        ),
        migrations.AddField(
            model_name='singleintegeranswer',
            name='by_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='singleintegeranswer',
            name='for_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SIA', to='Management.Question'),
        ),
        migrations.AddField(
            model_name='scorelineanswerset',
            name='for_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.Question'),
        ),
        migrations.AddField(
            model_name='scorelineanswer',
            name='by_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scorelineanswer',
            name='for_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SA', to='Management.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_set_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Answer_Set_Type', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Answer_Type', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='question',
            name='for_matchday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.Matchday'),
        ),
        migrations.AddField(
            model_name='matchday',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seasons.AllSeason'),
        ),
        migrations.AddField(
            model_name='lineupanswerset',
            name='for_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.Question'),
        ),
        migrations.AddField(
            model_name='lineupanswer',
            name='by_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lineupanswer',
            name='for_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LA', to='Management.Question'),
        ),
        migrations.AddField(
            model_name='groupranksanswerset',
            name='for_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.Question'),
        ),
        migrations.AddField(
            model_name='groupranksanswer',
            name='by_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupranksanswer',
            name='for_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GRA', to='Management.Question'),
        ),
        migrations.AddField(
            model_name='goalandassistanswerset',
            name='for_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.Question'),
        ),
        migrations.AddField(
            model_name='goalandassistanswer',
            name='by_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goalandassistanswer',
            name='for_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GAAA', to='Management.Question'),
        ),
    ]
