# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_auto_20170210_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalandassistanswer',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='groupranksanswer',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lineupanswer',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scorelineanswer',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='singleintegeranswer',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='singleplayerteamanswer',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamandvalueanswer',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='windrawloseanswer',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='yesnoanswer',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
