# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_auto_20170212_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineupanswer',
            name='team',
            field=models.CharField(default='Manchester United', max_length=30),
            preserve_default=False,
        ),
    ]
