# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-01 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Participation', models.CharField(choices=[('Team', 'Team'), ('Indi', 'Individual')], default='Indi', max_length=4)),
                ('Current', models.BooleanField(default=True)),
            ],
        ),
    ]
