# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchdayPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.IntegerField(editable=False)),
                ('question_2', models.IntegerField(editable=False)),
                ('question_3', models.IntegerField(editable=False)),
                ('question_4', models.IntegerField(editable=False)),
                ('question_5', models.IntegerField(editable=False)),
                ('question_6', models.IntegerField(editable=False)),
                ('question_7', models.IntegerField(editable=False)),
                ('question_8', models.IntegerField(editable=False)),
                ('question_9', models.IntegerField(editable=False)),
                ('question_10', models.IntegerField(editable=False)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.Matchday')),
            ],
        ),
    ]
