# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Management', '0001_initial'),
        ('Player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchdayPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_1', models.IntegerField(editable=False)),
                ('Question_2', models.IntegerField(editable=False)),
                ('Question_3', models.IntegerField(editable=False)),
                ('Question_4', models.IntegerField(editable=False)),
                ('Question_5', models.IntegerField(editable=False)),
                ('Question_6', models.IntegerField(editable=False)),
                ('Question_7', models.IntegerField(editable=False)),
                ('Question_8', models.IntegerField(editable=False)),
                ('Question_9', models.IntegerField(editable=False)),
                ('Question_10', models.IntegerField(editable=False)),
                ('Matchday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Management.Matchday')),
                ('Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Player.Profile')),
            ],
        ),
    ]
