# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 14:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Performance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdaypoint',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
